name: Build App (Manual)
on:
  workflow_dispatch:
    inputs:
      os:
        type: choice
        description: OS to build on. Ubuntu is faster, MacOS supports iOS builds, Windows is unsupported
        options:
          - macos-latest
          - ubuntu-latest
      platform:
        type: choice
        description: Platform to build for
        options:
          - android
          - ios
      profile:
        type: choice
        description: Build profile to use
        options:
          - development
          - preview
  workflow_call:
    inputs:
      os:
        type: string
        required: true
      platform:
        type: string
        required: true
      profile:
        type: string
        required: true
jobs:
  build:
    runs-on: ${{ inputs.os }}
    steps:
      - name: 🏗 Setup repo
        uses: actions/checkout@v3

      - name: 🏗 Setup Node
        uses: actions/setup-node@v3
        with:
          node-version: 18.x

      - name: 🏗 Setup Expo and EAS
        uses: expo/expo-github-action@v7
        with:
          token: ${{ secrets.EXPO_TOKEN }}
          expo-version: latest
          eas-version: latest

      - name: 🏗 Setup EAS local builds
        run: yarn global add eas-cli-local-build-plugin

      - name: 📦 Install dependencies (root)
        run: |
          npm ci

      - name: 📦 Install dependencies
        working-directory: packages/expo
        run: |
          npm ci

      - name: 🧪 Run checks
        working-directory: packages/expo
        run: |
          ./node_modules/.bin/tsc --noEmit

      - name: 👷 Build app
        working-directory: packages/expo
        run: |
          eas build --local \
            --non-interactive \
            --platform=${{ inputs.platform }} \
            --profile=${{ inputs.profile }}

      - name: 📱 Upload binary
        uses: actions/upload-artifact@v3
        with:
          name: app-${{ inputs.platform }}-${{ inputs.profile }}
          path: packages/expo/build-*
